#Plugin By Callahan
#----------------------------------
#%timer% = time remaining:)
#all times are in ticks (20 ticks = 1 second)
#github: Call4han
#any bug report me through the discord: https://discord.com/invite/y3jwVFbvsx
Cooldown-Item: 10 #In Seconds
Cooldown-Message: "&cYou must wait &6%timer% &cSeconds to use this item"
#----------------------------------
#Lightning
Lightning-fire-time: 1
#Fireball
#-------
#Dragon-SHOOT
#------
#Arrow
Type-Arrow: "SLOWNESS"
Arrow-Damage: 2
Pickup-Arrow: "ALLOWED" #ALLOWED, DISALLOWED, CREATIVE_ONLY
#TNT
TNT-time-explosion: 5
#Triident
Trident-Pickup: "ALLOWED" #ALLOWED, DISALLOWED, CREATIVE_ONLY
Trident-Damage: 2
#Firework
Firework-Type: "CREEPER" #BALL, BALL_LARGE, BURST, CREEPER, STAR
Firework-Power: 2 #1-5
#Skull-wither
Skull-effect: true
#Snowball
#_-------
#Throwing
Potion-Type: "SPEED"
Potion-Duration: 100 #in ticks (20 ticks = 1 second)
Potion-Amplifier:
#Types-Potion:
  #ABSORPTION
  #BAD_OMEN
  #BLINDNESS
  #CONDUIT_POWER
  #CONFUSION
  #DAMAGE_RESISTANCE
  #DARKNESS
  #DOLPHINS_GRACE
  #FAST_DIGGING
  #FIRE_RESISTANCE
  #GLOWING
  #HARM
  #HEAL
  #HEALTH_BOOST
  #HERO_OF_THE_VILLAGE
  #HUNGER
  #INCREASE_DAMAGE
  #INVISIBILITY
  #JUMP
  #LEVITATION
  #LUCK
  #NIGHT_VISION
  #POISON
  #REGENERATION
  #SATURATION
  #SLOW
  #SLOW_DIGGING
  #SLOW_FALLING
  #UNLUCK
  #WATER_BREATHING
  #WEAKNESS
  #WITHER
